=== gusvmx/BmvMQ/bmvMQ-api/src/main/resources/bmvMq.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="bmvMq">
		<xs:complexType>
			<xs:all>
				<xs:element name="clientId" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="username" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="password" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="acknowledgeMode" type="acknowledgeModeType" minOccurs="1" maxOccurs="1" default="AUTO_ACKNOWLEDGE" />
				<xs:element name="reconnectionInterval" type="xs:int" minOccurs="1" maxOccurs="1" default="5000"/>
				<xs:element name="maxConnections" type="xs:int" minOccurs="1" maxOccurs="1" default="8"/>
				<xs:element name="asyncSend" type="xs:boolean" minOccurs="0" maxOccurs="1" default="true"/>
				<xs:element name="errorHandlerClassName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="acknowledgeModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AUTO_ACKNOWLEDGE" />
			<xs:enumeration value="CLIENT_ACKNOWLEDGE" />
			<xs:enumeration value="DUPS_OK_ACKNOWLEDGE" />
			<xs:enumeration value="SESSION_TRANSACTED"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== gusvmx/BmvMQ/bmvMQ/src/test/resources/bmvMqJNDI.xml
<?xml version="1.0" encoding="UTF-8"?>
<bmvMq xsi:noNamespaceSchemaLocation="bmvMq.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<url>vm://localhost?broker.persistent=false</url>
	<username>admin</username>
	<password>admin</password>
	<acknowledgeMode>AUTO_ACKNOWLEDGE</acknowledgeMode>
	<destinationResolver>JNDI</destinationResolver>
	<reconnectionInterval>5000</reconnectionInterval>
	<maxConnections>8</maxConnections>
</bmvMq>

=== gusvmx/BmvMQ/bmvMQ-amq/src/test/resources/bmvMq.xml
<?xml version="1.0" encoding="UTF-8"?>
<bmvMq xsi:noNamespaceSchemaLocation="bmvMq.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<url>${test.broker.url}</url>
	<clientId>${test.broker.clientId}</clientId>
	<username>${test.broker.username}</username>
	<password>${test.broker.password}</password>
	<acknowledgeMode>AUTO_ACKNOWLEDGE</acknowledgeMode>
	<reconnectionInterval>${test.broker.reconnectionInterval}</reconnectionInterval>
	<maxConnections>${test.broker.maxConnections}</maxConnections>
	<asyncSend>true</asyncSend>
</bmvMq>

=== gusvmx/BmvMQ/bmvMQ-amq/src/test/resources/bmvMqThroughput.xml
<?xml version="1.0" encoding="UTF-8"?>
<bmvMq xsi:noNamespaceSchemaLocation="bmvMq.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<url>tcp://10.100.232.221:61617</url>
<!-- 	<url>tcp://10.100.79.157:61616</url> -->
	<clientId>bmv-mq-performance-test</clientId>
	<username>admin</username>
	<password>admin</password>
	<acknowledgeMode>AUTO_ACKNOWLEDGE</acknowledgeMode>
	<reconnectionInterval>5000</reconnectionInterval>
	<maxConnections>3</maxConnections>
</bmvMq>
